services:
  chat-server:
    container_name: chat-server
    build:
      context: .
      dockerfile: ./server.Dockerfile
    ports:
      - "50000:50000"
      - "50002:50001"
    restart: always

  chat-client:
    container_name: chat-client
    build:
      context: .
      dockerfile: ./client.Dockerfile
    ports:
      - "50001:50001"
    restart: always
