services:
  chat-server:
    container_name: chat-server
    build: .
    volumes:
      - .:/app
    ports:
      - "50000:50000"
    restart: always
    command: python -m app.server 0.0.0.0:50000 "EasyTask-Instance-1"

  chat-server-2:
    container_name: chat-server-2
    build: .
    volumes:
      - .:/app
    ports:
      - "50001:50000"
    restart: always
    command: python -m app.server 0.0.0.0:50000 "EasyTask-Instance-2"

  chat-client:
    container_name: chat-client
    build: .
    volumes:
      - .:/app
    ports:
      - "60000:60000"
    command: python -m app.client_cli
